drop database individual_project_1;
create database individual_project_1;
use	individual_project_1;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `individual_project_1`.`usuario` (
  `idusuario` INT NOT NULL auto_increment,
  `Name` VARCHAR(45) NOT NULL,
  `NickName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `FotoPerfil` CHAR(1) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `NickName_UNIQUE` (`NickName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO usuario (`Name`, NickName, email, senha, FotoPerfil) 
	value 
	('Miguel Soneti','Hiru','miguelsonetimauer@gmail.com','Hz2904','3');

CREATE TABLE IF NOT EXISTS `individual_project_1`.`trofeus` (
  `idtrofeu` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`idtrofeu`))
ENGINE = InnoDB;

INSERT INTO trofeus (idtrofeu, nome, `desc`) VALUES
(1, 'Eu Escolho Você!', 'pegar o 1º inicial e derrotar o Blue'),
(2, 'Pedra Esfarelada!', 'derrotar o primeiro líder de gináso BROK'),
(3, 'O que a misty fez? Nada', 'derrotar a segunda lidere de ginásio'),
(4, 'Energia 0!', 'derrote o terceiro líder de ginásio LT'),
(5, 'Planta Podada!', 'derrote a quarta líder de ginásio ÉR'),
(6, 'Névoa ofuscada', 'derrote o quinto líder de ginásio KO'),
(7, 'Mente Fraca', 'derrote a sexta líder de ginásio SAB'),
(8, 'Um balde de água gelada', 'derrote o sétimo líder de ginásio'),
(9, 'Equipe Rocket Decolando pela ultima vez!', 'derrote o último líder de ginásio'),
(10, 'Raspadinha!!!', 'derrote a primeira da elite dos 4 LO'),
(11, 'Verdadeiro Faixa Preta', 'derrote o segundo da elite dos 4 BR'),
(12, 'Fantasma, ta com medo?', 'derrote a terceira da elite dos 4 A'),
(13, 'Like a dragon!', 'derrote o último da elite dos 4 LAN'),
(14, 'O Verdadeiro Campeão', 'derrotar Blue pela última vez'),
(15, 'Eu Sou Você? ...', 'derrote RED no MT. Silver'),
(16, 'Só pássaro e ratos?', 'Captute todos os pokémon da rota 1'),
(17, 'Longe de casa', 'Capture todos os pokemon da rota 2'),
(18, 'Terceiro passo rumo a glória!', 'Capture todos os pokemon da rota 3'),
(19, 'Aqui é meio próximo da Lua', 'Capture todos os pokemon da rota 4'),
(20, 'Um túnel?', 'Capture todos os pokemon da rota 5'),
(21, 'Rumo ao mar!', 'Capture todos os pokemon da rota 6'),
(22, 'Novos resgistros', 'Capture todos os pokemon da rota 7'),
(23, 'Só bixo brabo', 'Capture todos os pokemon da rota 8'),
(24, 'Sempre os mesmos?', 'Capture todos os pokemon da rota 9'),
(25, 'Ta meio escuro por aqui', 'Capture todos os pokemon da rota 10'),
(26, 'Aqui é o limite?', 'Capture todos os pokemon da rota 11'),
(27, 'Por que aqui tem um urso hibernando?', 'Capture todos os pokemon da rota 12'),
(28, 'Sempre os mesmos?', 'Capture todos os pokemon da rota 13'),
(29, 'Não há nada a ser ditto', 'Capture todos os pokemon da rota 14'),
(30, 'Essa bola rosa INÚTIL', 'Capture todos os pokemon da rota 15'),
(31, 'Uma gangue de motoqueiros?', 'Capture todos os pokemon da rota 16'),
(32, 'Me patrocina Red Bull', 'Capture todos os pokemon da rota 17'),
(33, 'Ta começando a ficar fácil', 'Capture todos os pokemon da rota 18'),
(34, 'Os meus inimigos estão la!', 'Capture todos os pokemon da rota 19'),
(35, 'Ta sentindo o frio?', 'Capture todos os pokemon da rota 20'),
(36, 'De volta em casa', 'Capture todos os pokemon da rota 21'),
(37, 'Tão perto, mas tão longe', 'Capture todos os pokemon da rota 22'),
(38, 'Ah shit, here we go again', 'Capture todos os pokemon da rota 23'),
(39, 'Você quer me recrutar?', 'Capture todos os pokemon da rota 24'),
(40, 'O que voce é bill?', 'Capture todos os pokemon da rota 25'),
(41, 'ColecionadorI', 'Registre 10 pokemon na sua pokedex'),
(42, 'ColecionadorII', 'Registre 30 pokemon na sua pokedex'),
(43, 'ColecionadorIII', 'Registre 60 pokemon na sua pokedex'),
(44, 'ColecionadorIV', 'Registre 100 pokemon na sua pokedex'),
(45, 'ColecionadorV', 'Registre 125 pokemon na sua pokedex'),
(46, 'Eu realizei o seu sonho professor!', 'Registre 150 pokemon na sua pokedex'),
(47, 'Ventos Gelados', 'Capture o pokemon lendário Articuno'),
(48, 'Ventos da tempestade', 'Capture o pokemon lendário Zapdos'),
(49, 'Ventos Quentes', 'Capture o pokemon lendário Moltres'),
(50, 'Eu te entendo', 'Capture o pokemon lendário Mewtwo'),
(51, 'Existe mais um?', 'Capture o pokemon mítico Mew'),
(52, 'Nossos Limites vão muito além de Kanto', 'Obtenha todos os troféus do jogo');

CREATE TABLE IF NOT EXISTS `individual_project_1`.`relacionamento_trofeus` (
  `usuario_idusuario` INT NOT NULL,
  `trofeu_idtrofeu` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `trofeu_idtrofeu`),
  INDEX `fk_relacionamento_trofeu1_idx` (`trofeu_idtrofeu` ASC) VISIBLE,
  CONSTRAINT `fk_relacionamento_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `individual_project_1`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relacionamento_trofeu1`
    FOREIGN KEY (`trofeu_idtrofeu`)
    REFERENCES `individual_project_1`.`trofeus` (`idtrofeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into relacionamento_trofeus values 
	(1,1),
    (1,2),
    (1,3),
    (1,4),
    (1,5),
    (1,6),
    (1,7),
    (1,8),
    (1,9),
    (1,10),
    (1,11),
    (1,12),
    (1,13),
    (1,14),
    (1,15),
    (1,16),
    (1,17),
    (1,18),
    (1,19),
    (1,20),
    (1,21),
    (1,22),
    (1,23),
    (1,24),
    (1,25),
    (1,26),
    (1,27),
    (1,28),
    (1,29),
    (1,30),
    (1,31),
    (1,32),
    (1,33),
    (1,34),
    (1,35),
    (1,36),
    (1,37),
    (1,38),
    (1,39),
    (1,40),
    (1,41),
    (1,42),
    (1,43),
    (1,44),
    (1,45),
    (1,46),
    (1,47),
    (1,48),
    (1,49),
    (1,50),
    (1,51),
    (1,52);

CREATE TABLE IF NOT EXISTS `individual_project_1`.`pokemons` (
  `id` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO pokemons (id, Name) VALUES
(1, 'Bulbasaur'),
(2, 'Ivysaur'),
(3, 'Venusaur'),
(4, 'Charmander'),
(5, 'Charmeleon'),
(6, 'Charizard'),
(7, 'Squirtle'),
(8, 'Wartortle'),
(9, 'Blastoise'),
(10, 'Caterpie'),
(11, 'Metapod'),
(12, 'Butterfree'),
(13, 'Weedle'),
(14, 'Kakuna'),
(15, 'Beedrill'),
(16, 'Pidgey'),
(17, 'Pidgeotto'),
(18, 'Pidgeot'),
(19, 'Rattata'),
(20, 'Raticate'),
(21, 'Spearow'),
(22, 'Fearow'),
(23, 'Ekans'),
(24, 'Arbok'),
(25, 'Pikachu'),
(26, 'Raichu'),
(27, 'Sandshrew'),
(28, 'Sandslash'),
(29, 'Nidoran♀'),
(30, 'Nidorina'),
(31, 'Nidoqueen'),
(32, 'Nidoran♂'),
(33, 'Nidorino'),
(34, 'Nidoking'),
(35, 'Clefairy'),
(36, 'Clefable'),
(37, 'Vulpix'),
(38, 'Ninetales'),
(39, 'Jigglypuff'),
(40, 'Wigglytuff'),
(41, 'Zubat'),
(42, 'Golbat'),
(43, 'Oddish'),
(44, 'Gloom'),
(45, 'Vileplume'),
(46, 'Paras'),
(47, 'Parasect'),
(48, 'Venonat'),
(49, 'Venomoth'),
(50, 'Diglett'),
(51, 'Dugtrio'),
(52, 'Meowth'),
(53, 'Persian'),
(54, 'Psyduck'),
(55, 'Golduck'),
(56, 'Mankey'),
(57, 'Primeape'),
(58, 'Growlithe'),
(59, 'Arcanine'),
(60, 'Poliwag'),
(61, 'Poliwhirl'),
(62, 'Poliwrath'),
(63, 'Abra'),
(64, 'Kadabra'),
(65, 'Alakazam'),
(66, 'Machop'),
(67, 'Machoke'),
(68, 'Machamp'),
(69, 'Bellsprout'),
(70, 'Weepinbell'),
(71, 'Victreebel'),
(72, 'Tentacool'),
(73, 'Tentacruel'),
(74, 'Geodude'),
(75, 'Graveler'),
(76, 'Golem'),
(77, 'Ponyta'),
(78, 'Rapidash'),
(79, 'Slowpoke'),
(80, 'Slowbro'),
(81, 'Magnemite'),
(82, 'Magneton'),
(83, 'Farfetch''d'),
(84, 'Doduo'),
(85, 'Dodrio'),
(86, 'Seel'),
(87, 'Dewgong'),
(88, 'Grimer'),
(89, 'Muk'),
(90, 'Shellder'),
(91, 'Cloyster'),
(92, 'Gastly'),
(93, 'Haunter'),
(94, 'Gengar'),
(95, 'Onix'),
(96, 'Drowzee'),
(97, 'Hypno'),
(98, 'Krabby'),
(99, 'Kingler'),
(100, 'Voltorb'),
(101, 'Electrode'),
(102, 'Exeggcute'),
(103, 'Exeggutor'),
(104, 'Cubone'),
(105, 'Marowak'),
(106, 'Hitmonlee'),
(107, 'Hitmonchan'),
(108, 'Lickitung'),
(109, 'Koffing'),
(110, 'Weezing'),
(111, 'Rhyhorn'),
(112, 'Rhydon'),
(113, 'Chansey'),
(114, 'Tangela'),
(115, 'Kangaskhan'),
(116, 'Horsea'),
(117, 'Seadra'),
(118, 'Goldeen'),
(119, 'Seaking'),
(120, 'Staryu'),
(121, 'Starmie'),
(122, 'Mr. Mime'),
(123, 'Scyther'),
(124, 'Jynx'),
(125, 'Electabuzz'),
(126, 'Magmar'),
(127, 'Pinsir'),
(128, 'Tauros'),
(129, 'Magikarp'),
(130, 'Gyarados'),
(131, 'Lapras'),
(132, 'Ditto'),
(133, 'Eevee'),
(134, 'Vaporeon'),
(135, 'Jolteon'),
(136, 'Flareon'),
(137, 'Porygon'),
(138, 'Omanyte'),
(139, 'Omastar'),
(140, 'Kabuto'),
(141, 'Kabutops'),
(142, 'Aerodactyl'),
(143, 'Snorlax'),
(144, 'Articuno'),
(145, 'Zapdos'),
(146, 'Moltres'),
(147, 'Dratini'),
(148, 'Dragonair'),
(149, 'Dragonite'),
(150, 'Mewtwo'),
(151, 'Mew');

CREATE TABLE IF NOT EXISTS `individual_project_1`.`relacionamento_pokemon` (
  `usuario_idusuario` INT NOT NULL,
  `pokemons_id` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `pokemons_id`),
  INDEX `fk_trelacionamentopokemon_pokemons1_idx` (`pokemons_id` ASC) VISIBLE,
  CONSTRAINT `fk_trelacionamentopokemon_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `individual_project_1`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trelacionamentopokemon_pokemons1`
    FOREIGN KEY (`pokemons_id`)
    REFERENCES `individual_project_1`.`pokemons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into relacionamento_pokemon values 
	(1,1),
    (1,2),
    (1,3),
    (1,4),
    (1,5),
    (1,6),
    (1,7),
    (1,8),
    (1,9),
    (1,10),
    (1,11),
    (1,12),
    (1,13),
    (1,14),
    (1,15),
    (1,16),
    (1,17),
    (1,18),
    (1,19),
    (1,20),
    (1,21),
    (1,22),
    (1,23),
    (1,24),
    (1,25),
    (1,26),
    (1,27),
    (1,28),
    (1,29),
    (1,30),
    (1,31),
    (1,32),
    (1,33),
    (1,34),
    (1,35),
    (1,36),
    (1,37),
    (1,38),
    (1,39),
    (1,40),
    (1,41),
    (1,42),
    (1,43),
    (1,44),
    (1,45),
    (1,46),
    (1,47),
    (1,48),
    (1,49),
    (1,50),
    (1,51),
    (1,52),
    (1,53),
    (1,54),
    (1,55),
    (1,56),
    (1,57),
    (1,58),
    (1,59),
    (1,60),
    (1,61),
    (1,62),
    (1,63),
    (1,64),
    (1,65),
    (1,66),
    (1,67),
    (1,68),
    (1,69),
    (1,70),
    (1,71),
    (1,72),
    (1,73),
    (1,74),
    (1,75),
    (1,76),
    (1,77),
    (1,78),
    (1,79),
    (1,80),
    (1,81),
    (1,82),
    (1,83),
    (1,84),
    (1,85),
    (1,86),
    (1,87),
    (1,88),
    (1,89),
    (1,90),
    (1,91),
    (1,92),
    (1,93),
    (1,94),
    (1,95),
    (1,96),
    (1,97),
    (1,98),
    (1,99),
    (1,100),
    (1,101),
    (1,102),
    (1,103),
    (1,104),
    (1,105),
    (1,106),
    (1,107),
    (1,108),
    (1,109),
    (1,110),
    (1,111),
    (1,112),
    (1,113),
    (1,114),
    (1,115),
    (1,116),
    (1,117),
    (1,118),
    (1,119),
    (1,120),
    (1,121),
    (1,122),
    (1,123),
    (1,124),
    (1,125),
    (1,126),
    (1,127),
    (1,128),
    (1,129),
    (1,130),
    (1,131),
    (1,132),
    (1,133),
    (1,134),
    (1,135),
    (1,136),
    (1,137),
    (1,138),
    (1,139),
    (1,140),
    (1,141),
    (1,142),
    (1,143),
    (1,144),
    (1,145),
    (1,146),
    (1,147),
    (1,148),
    (1,149),
    (1,150),
    (1,151);

CREATE TABLE IF NOT EXISTS `individual_project_1`.`Treiners` (
  `usuario_idusuario` INT NOT NULL,
  `pokedex` INT NULL,
  `catchMultiplier` INT NULL,
  `TrainerDamage` INT NULL,
  `TrainerLife` INT NULL,
  `Badges` INT NULL,
  `Elite` INT NULL,
  `Champeon` VARCHAR(45) NULL,
  `qtdPokeballs` INT NULL,
  PRIMARY KEY (`usuario_idusuario`),
  CONSTRAINT `fk_Treiners_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `individual_project_1`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into treiners value 
	(1,151,4,200,1000,8,4,'true',10);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
